#!/bin/bash

# Containers deletion script

echo "Before execute this script first make sure Docker service is running."
read -p "Press Ctrl+C to cancel or other key to continue"

clear
# Container deletion
echo "-----------------------"
echo "| DELETING CONTAINERS |"
echo "-----------------------"
docker container stop scs-postfix-cont
docker container stop scs-apache-cont
docker container stop scs-mysql-cont
docker container stop scs-bind9-cont

docker container rm scs-postfix-cont
docker container rm scs-apache-cont
docker container rm scs-mysql-cont
docker container rm scs-bind9-cont