-- DB CREATION
DROP DATABASE IF EXISTS scs;
CREATE DATABASE scs;

USE scs;

-- TABLE CREATION
CREATE TABLE testdb(
id INT AUTO_INCREMENT,
name VARCHAR(25) NOT NULL,
lastname VARCHAR(50) NOT NULL,
reg_date DATE DEFAULT '0001-01-01' NOT NULL,
CONSTRAINT pk_employees PRIMARY KEY (id)
);

INSERT INTO testdb
(name,lastname,reg_date)
VALUES ('AdminTest','AdminTest','2023-02-02');


-- USER CREATION FOR APACHE/PHP CONTAINER ACCESS
CREATE USER 'root'@'scs-apache-cont' IDENTIFIED BY 'debian';
FLUSH PRIVILEGES;